### ISSUE TITLE
Prachtig

### ISSUE THREAD

**Issue by vasilisvg** [Jamerrone/cssttr#1]
https://github.com/Jamerrone/cssttr/blob/4fd1f05ead89d22e23a3d5caa4ac8c36de0f20fa/main.css#L1
Erg mooie, nette CSS. Goed leesbaar. Je schrijft goede selectors: niet te specifiek, gewoon precies goed. Leuke experimenten ook. Ga zo door!

**Comment by Jamerrone** [comment]
Thanks!
